
         
         var rollToName = {
            "001": "Suraj Santosh Gujar",
        "002": "Rinkita Santosh Gujar",
        "003": "Dipali Mahadeo Kajle",
        "004": "Shivangi Shitalaprasad Khairwar",
        "005": "Raj Rajendra Ansurkar",
        "006": "Harsh Bharat Shelar",
        "007": "Reshma Pramod Chauhan",
        "008": "Mohd Nawaz Haroon Shaikh",
        "009": "Shoaib Chand Mohammad Shaikh",
        "010": "Saniya Waris Ansari",
        "011": "Sudhanshu Somnath Shelar",
        "012": "Saurav Madan Jha",
        "013": "Rohit Dhanpat Vishwakarma",
        "014": "Karan Narayan Singh",
        "015": "Abhishek Ashok Sahu",
        "016": "Alfaiz Farid Khan",
        "017": "Mohammeduzair Farid Khan",
        "018": "Sohit Ashokkumar Varma",
        "019": "Rohit Dharmendra Vishwakarma",
        "020": "Supriya Sanjay Maurya",
        "021": "Shivam Surendra Gaud",
        "022": "Muskan Mohammed Tahir Nidaf",
        "023": "Sahil Prashant Sawant",
        "024": "Sohaib Mubeen Khan",
        "025": "Krushna Dattaram Chavan",
        "026": "Purva Uttam Mulik",
        "027": "Darshana Sudhir Tukrul",
        "028": "Bhumi Rajesh Bhatkar",
        "029": "Mohit Ramesh Vyas",
        "030": "Irfan Kalam Ansari",
        "031": "Mayur Anil Munde",
        "032": "Mahmood Maqsood Shaikh",
        "033": "Anjali Shrinath Gupta",
        "034": "S Elayaraja Sadaiyanmuthu",
        "035": "Dhruv Radheshyam Singh",
        "036": "Afsana Md. Alisher Khatun",
        "037": "Omkar Mahadev Veer",
        "038": "Omkar Ashok Komu",
        "039": "Neha Jaiprakash Gupta",
        "040": "Saurabh Dadasaheb Chede",
        "041": "Namrata Sambhaji Pawar",
        "042": "Nikhil Lalit Maru",
        "043": "Sakib Shahid Shaikh",
        "044": "Sujal Ram Somavase",
        "045": "Vaishnavi Dayanand Atkhile",
        "046": "Ismail Mehboob Shaikh",
        "047": "Komal Gurudatt Pednekar",
        "048": "Sonali Arjun Dandge",
        "049": "Kirti Mangesh Prabhulkar",
        "050": "Harsh Subhash Bidlan",
        "051": "Imran Hafiz Alimuddin Ansari",
        "052": "Shani Vijay Bahadur Yadav",
        "053": "Altaf Ahmed Mohd Samsad Shaikh",
        "054": "Sahil Surajbhan Shreevastav",
        "055": "Neeraj Irapa Mallapule",
        "056": "Priyanshu Narendra Verma",
        "057": "Satyam Surendra Gaud",
        "058": "Shubham Nitin Golatkar",
        "059": "Smit Santosh Sawant",
        "060": "Shirtaj Aslam Siddiqui",
        "061": "Nazmul Moshiar Purkait",
        "062": "Mohammed Nizam Akhtar Ali Shaikh",
        "063": "Anas Habibullah Khan",
        "064": "Rima Jitesh Makwana",
        "065": "Henry Harry Denis",
        "066": "Ravi Madanlal Suthar",
        "067": "Abdul Hamid Abdul Khalid Shaikh",
        "068": "Nisha Amar Gupta",
        "069": "Afzal Abdul Hak Ansari",
        "070": "Afzal Arshad Ansari",
        "071": "Harsh Satish Parab",
        "072": "Avinash Arvind Vishwakarma",
        "073": "Faiz Riyaz Khan",
        "074": "Ayush Mahesh Labde",
        "075": "Gauri Santosh Ghadi",
        "076": "Zeenat Sadique Shaikh",
        "077": "Sahil Ganpat Sawant",
        "078": "Nazneen Nazir Hussain Shaikh",
        "079": "Ayub Dosani Ar"

        };
// tumi aanki student add kru kskta
